In [1]:
import numpy as np
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [2]:
np.arange(1,10.1,3)

array([ 1.,  4.,  7., 10.])

In [12]:
np.ones([5,2],dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [5]:
x = np.arange(5)
x.dtype
print(x)
print(x.dtype)
print(x.itemsize)

[0 1 2 3 4]
int32
4


In [16]:
print(np.arange(1,10.1,2,dtype=int))

[1 3 5 7 9]


In [17]:
x = np.arange(1, 5.0, 0.25)
print(x)
print(x.dtype)
print(x.itemsize)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75]
float64
8


In [19]:
np.arange(0)

array([], dtype=int32)

In [21]:
np.arange(8,2,-1)

array([8, 7, 6, 5, 4, 3])

In [25]:
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
a1 = np.array([[(1,2,3),(4,5,6)],((1,2,3),(4,5,6))])
print(a.ndim,a)
print(a1.ndim,a1)

2 [[1 2 3]
 [4 5 6]]
3 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [26]:
# if you provide equal values for start and stop, 
# then you will get an empty array
print(np.arange(0))
np.arange(2,2)
np.arange(8,2,1)
np.arange(2,8,-1)

[]


array([], dtype=int32)

In [30]:
# itemsize
# •calculate the byte size of each element
import numpy as np
a = np.array([(1,2,3),(1,2,3)])
print(a.itemsize*a.size)

24


In [28]:
# dtype
# •find the data type of the elements that are stored in anarray. So, if you want to know the data type of a particular element, you can use‘dtype’ function which will print the datatypealong with the size.
import numpy as np
a = np.array([(1,2,3)])
print(a.dtype)

int32


In [39]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
b = a.reshape(3,2)
print(b)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [59]:
print(a[0,2])

10


In [61]:
#It has printed 10 values between 1 to 3
import numpy as np
a=np.linspace(1,4,10)
print(a)

[1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.         3.33333333 3.66666667 4.        ]


In [62]:
import numpy as np
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


In [63]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [64]:
a1 = np.arange(1,13)
a2 = np.arange(13,25)
print(np.stack((a1,a2)))
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))
print(np.stack((a1,a2), axis = 1))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]
 [12 24]]


In [65]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]
